### ISSUE TITLE
How can I implement a run-time conditional dependency?

### ISSUE THREAD

**Issue by bradley-harden-apl** [kornelski/cargo-deb#29]
This is probably a little off-topic for `cargo-deb`, because it's ultimately a Debian packaging question. But I thought I would ask here, because I don't really know where else to ask. Please feel free to close if you think it's too off-topic.

I've read through some of the Debian packaging documentation and searched around the internet, but I can't seem to find an example that fits my situation.

I have a Rust application that normally depends on packages A and B. However, if hardware virtualization is not supported on the machine (for instance, it's a virtual machine that doesn't support nested virtualization), then package B is unnecessary. I would like to somehow dynamically change my dependencies based on whether the machine supports hardware virtualization. Do you have any idea how I could implement that?

Right now, I'm using an install script that does something like this

```bash
if $(grep -E 'svm|vmx' /proc/cpuinfo > /dev/null 2>&1); then
    HAS_VIRTUALIZATION=true
else
    HAS_VIRTUALIZATION=false
fi
```

But I would really like to turn this into a proper package.

**Comment by kornelski** [comment]
If you use weak linking and/or `dlopen`, it should work. Just don't specify the optional dependency at all. If you don't link to it using the usual program-breaking way, then cargo-deb's auto dependency feature won't see it either.

I think to handle it "properly" Debian uses multiple separate packages for optional features and some combinations of virtual packages and `provides` relationships, but cargo-deb doesn't bother with that.

**Comment by bradleyharden** [comment]
Sorry, I should probably explain a bit more.

My application is little more than a glorified bash script. It actually started as a bash script until I realized it would end up being too complicated, and I wanted actual types and data structures.

The application manages a series of tools run with Docker/Podman containers or with Vagrant and VirtualBox as full VMs. Right now, I use [duct](https://docs.rs/duct/latest/duct/) to control everything through process calls to those tools.

However, if hardware virtualization isn't enabled, then Vagrant and VirtualBox won't work anyway and aren't necessary. That just means any tools provided as VMs won't be available on that machine, which isn't a huge limitation, since most are available as containers.

So dlopen isn't really an option for me. I was imagining the solution would be something along the lines of the second approach you described. But I don't want users to have to manually check for hardware virtualization and modify their selected packages. I would like that to be handled on my end. What I don't know how to do is dynamically change the required packages based on that check.

**Comment by kornelski** [comment]
As far as I know, package dependencies in Debian are always a static declarative thing. They're an immutable constant for a .deb file. If you want different dependencies, then you create multiple .deb files, and build higher-level mechanism to choose which deb to install.

**Comment by bradley-harden-apl** [comment]
Yes, I think I came to that conclusion after a separate conversation elsewhere. I think I will do exactly what you describe. Thanks for your help. Sorry for the spam.
